# This is a config for E2B sandbox template.
# You can use template ID (tak9up93qcpurwe0b8cu) or template name (luci-ai-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("luci-ai-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("luci-ai-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('luci-ai-nextjs')

team_id = "1ddcf0f6-62a1-4fd7-86c4-f17405cb95a5"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "luci-ai-nextjs"
template_id = "tak9up93qcpurwe0b8cu"
